<!DOCTYPE html>
<html>
<head>
    ## Set the default character encoding
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    #parse("includes/css-files.inc")

    <style>
        body {font-family: Arial; font-size:12pt;}

        ## Included the box-sizing as it seem to allow images that have been dropped in by the froala
        ## editor to appear
        * {
            -webkit-box-sizing: content-box;
            -moz-box-sizing: content-box;
            box-sizing: content-box;
        }

    </style>
</head>
<body>
