/*
 ***************************************************************************
 *
 * Copyright (c) Greater London Authority, 2020. This source code is licensed under the Open Government Licence 3.0.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM.
 *
 ****************************************************************************
 */
package com.pivotal.utils;

import javax.servlet.http.HttpServletRequest;
import java.io.File;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * A class that wraps the results of a report or transformer run
 */
public class ExecutionResults {

    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(ExecutionResults.class);

    private String message;
    private String error;
    private String information;
    private int count;
    private int code;
    private Map<String,String> values;
    private String webserviceReportContent;
    private File webserviceReportContentFile;
    private String contentType;

    /**
     * Initialises the object
     */
    public ExecutionResults() {
        values=new LinkedHashMap<>();
    }

    /**
     * Initialises the object
     *
     * @param request Current request object
     */
    public ExecutionResults(HttpServletRequest request) {
        values=new LinkedHashMap<>();
    }

    /**
     * Returns the message
     *
     * @return String message
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message
     *
     * @param message String message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Returns the error message
     *
     * @return String message
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error message
     *
     * @param error String message
     */
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Returns the information string
     *
     * @return String information
     */
    public String getInformation() {
        return information;
    }

    /**
     * Sets the information message
     *
     * @param information String mesage
     */
    public void setInformation(String information) {
        this.information = information;
    }

    /**
     * Returns the count value
     *
     * @return int value
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the count value
     *
     * @param count int value
     */
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * Returns the code value
     *
     * @return int value
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the code value
     *
     * @param code int value
     */
    public void setCode(int code) {
        this.code = code;
    }

    /**
     * Gets the value of the specified token
     *
     * @param name Name of the token
     *
     * @return String value of the token
     */
    public String getValue(String name) {
        return values.get(name);
    }

    /**
     *  Sets the value of the specified token
     *
     * @param name Name of the token
     * @param value String value of the token
     */
    public void setValue(String name, String value) {
        values.put(name, value);
    }

    /**
     * Returns true if there is an error present
     *
     * @return Boolean
     */
    public boolean getInError() {
        return !Common.isBlank(error);
    }

    /**
     * Gets the output of the report that was run for a webservice endpoint
     *
     * @return Report output
     */
    public String getWebserviceReportContent() {
        return webserviceReportContent;
    }

    /**
     * Sets the value of the report output generated by running a web service endpoint task
     *
     * @param webserviceReportContent Content
     */
    public void setWebserviceReportContent(String webserviceReportContent) {
        this.webserviceReportContent = webserviceReportContent;
    }

    /**
     * Gets the output of the report that was run for a webservice endpoint
     *
     * @return Report output file
     */
    public File getWebserviceReportContentFile() {
        return webserviceReportContentFile;
    }

    /**
     * Sets the value of the report output generated by running a web service endpoint task
     *
     * @param filename File containing report content
     */
    public void setWebserviceReportContentFile(File filename) {
        webserviceReportContentFile = filename;
    }

    /**
     * Returns the current content type for the returned data
     * This will be null unless the template has set it
     *
     * @return Content MIME type
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the content type of the returned data
     *
     * @param contentType MIME content type e.g. text/xml
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
}
